"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

// Fallback empty dictionaries if fetch fails or is incomplete
const defaultDictionaries: Record<string, any> = {
    tr: { 
        common: { save: "Kaydet", cancel: "İptal", welcome: "Hoş geldiniz", search: "Ara", delete: "Sil" },
        invoice: {
            successTitle: "E-Fatura Kesildi",
            successDesc: "Belge GİB kuyruğuna başarıyla eklendi. Müşteriye e-posta olarak otomatik iletilmiştir.",
            btnNew: "YENİ FATURA",
            btnPdf: "PDF OLARAK İNDİR",
            buyerLabel: "SAYIN / KURUM (ALICI)",
            searchCustomer: "Fatura Kesilecek Cari Ünvan veya Vergi No...",
            recentCustomers: "Son Kullanılan Cariler",
            balance: "Bakiye",
            taxOffice: "Vergi D.",
            undefined: "Tanımsız",
            changeCustomer: "Cariyi Değiştir",
            notSpecified: "Belirtilmemiş",
            noAddress: "Kayıtlı açık adres bulunamadı. Fatura E-Arşiv olarak kesilecektir.",
            invoiceType: "Fatura Tipi",
            typeSales: "SATIŞ FATURASI",
            typeReturn: "İADE FATURASI",
            typeTevkifat: "TEVKİFATLI FATURA",
            typeIstisna: "İSTİSNA FATURASI",
            scenario: "Senaryo",
            scenTicari: "TİCARİ FATURA",
            scenTemel: "TEMEL FATURA",
            currency: "Döviz",
            tcmbRate: "TCMB Kuru",
            issueDate: "Düzenlenme Tarihi",
            branch: "Şube / Kasa",
            branchMain: "Merkez (Online)",
            addDispatch: "E-İRSALİYE / REFERANS EKLE",
            dispatchNo: "İrsaliye Numarası",
            dispatchPlaceholder: "16 Haneli Belge No",
            dispatchDate: "İrsaliye Tarihi",
            thDesc: "Ürün / Hizmet Açıklaması",
            thQty: "Miktar",
            thPrice: "Birim Fiyat",
            thDiscount: "İsk.(%)",
            thIsCode: "İstisna Kodu",
            thOtherTaxes: "Diğer Vergiler",
            thVat: "KDV(%)",
            thTevkifat: "Tevkifat",
            thNet: "Net Tutar",
            itemSearch: "Açıklama veya ürün adı...",
            stockSearchList: "🔍 Stok Arama Listesi",
            stockCards: "Stok Kartları",
            stock: "Stok",
            vat: "KDV",
            notFound: "Sonuç bulunamadı.",
            otvNone: "Ö.T.V Yok",
            otvPercent: "Yüzdesel ÖTV",
            otvAmount: "Maktu (Birim)",
            otvAmountLabel: "Tutar/Oran:",
            tevkifatNone: "Tevkifatsız",
            tevkifatFull: "10/10 (Tam)",
            addLine: "YENİ SATIR EKLE",
            noteLabel: "Fatura Alt Notu",
            notePlaceholder: "Banka IBAN bilgileri, teslimat notu vb...",
            totSub: "Mal / Hizmet Toplam Tutar",
            totDisc: "Toplam İskonto",
            totVat: "Hesaplanan KDV",
            totOtv: "Hesaplanan ÖTV",
            totOiv: "Hesaplanan OİV",
            totTevkifat: "(-) Tevkif Edilen KDV",
            totGrand: "VERGİLER DAHİL TOPLAM",
            totSys: "Sistem (TL) Karşılığı",
            btnDraft: "TASLAK OLARAK KAYDET",
            btnDraftShort: "TASLAK",
            btnSend: "E-FATURALAŞTIR VE GÖNDER",
            btnWait: "BEKLEYİNİZ..."
        },
        adission: {
            successTitle: "E-Adisyon Yazdırıldı",
            successDesc: "hesabına ait elektronik adisyon başarıyla GİB'e iletildi ve mutfak fişi çıkarılıyor.",
            salon: "SALON (İÇ MEKAN)",
            teras: "TERAS",
            bahce: "BAHÇE",
            emptyCart: "Sepette ürün yok.",
            thProd: "Ürün",
            thQty: "Miktar",
            thTotal: "Tutar",
            statusNew: "Yeni",
            statusAvailable: "UYGUN",
            generalTotal: "Genel Toplam",
            btnPrinting: "YAZDIRILIYOR...",
            btnKitchen: "MUTFAK / BAR",
            btnClosing: "KAPATILIYOR...",
            btnCheckout: "HESABI KAPAT",
            standbyTitle: "Kasa Beklemede",
            standbyDesc: "İşlem yapmak için sol taraftan bir masa seçin.",
            minutes: "dk",
            unknown: "Belirsiz",
            emptyAdission: "Adisyon Boş",
            errEmpty: "Masaya henüz ürün eklenmemiş.",
            errKitchenEmpty: "Mutfağa iletilecek yeni bir ürün yok.",
            kitchenSuccess: "Mutfağa İletildi",
            kitchenSuccessDesc: "yeni ürün/istek IP mutfak yazıcısına başarıyla gönderildi."
        },
        terminal: {
            customer: "Cari",
            openAccount: "Açık Hesap",
            liveRateOn: "Canlı Kur Açık",
            liveRateOff: "Canlı Kur Kapalı",
            liveRateTooltip: "Aktif olduğunda ürünlerin döviz kurları anlık olarak TL'ye çevrilerek satışı yapılır.",
            coupon: "Kupon",
            points: "Puan",
            ref: "Ref",
            pending: "Bekleyen",
            quickSale: "Hızlı Satış",
            restoPos: "Resto-Pos",
            eInvoice: "E-Fatura",
            eMustahsil: "E-Müstahsil",
            eSmm: "E-SMM",
            retailCustomer: "Perakende Müşteri",
            customerSelection: "Müşteri Seçimi (F8)",
            searchPlaceholder: "Arama...",
            escClose: "ESC - Kapat",
            pendingSales: "Bekleyen Satışlar (F9)",
            noPendingSales: "Bekleyen satış yok.",
            openBtn: "AÇ",
            deleteBtn: "SİL",
            productsText: "Ürün",
            suspendSale: "Satışı Beklemeye Al",
            suspendLabelPlaceholder: "Etiket / İsim (Örn: Masa 5 veya Müşteri Adı)",
            btnSuspend: "Beklemeye Al",
            extrasDiscounts: "Ekstra & İndirimler",
            cartDiscount: "Sepet İndirimi",
            enterCode: "KOD GİRİN",
            usePoints: "Puan Kullan",
            available: "Kullanılabilir",
            orderNote: "Sipariş Notu / Referans",
            notePlaceholder: "Belge, plaka veya masa no...",
            confirm: "ONAYLA",
            completePayment: "Ödemeyi Tamamla",
            cartSubtotal: "Sepet Ara Toplam",
            manualDiscount: "Manuel İndirim / Puan",
            autoRewards: "Otomatik Kazanımlar",
            campaignDiscount: "Kampanya İndirimi",
            pointsToEarn: "Kazanılacak Parapuan",
            freeInCart: "Bedelsiz Sepette",
            grandTotal: "Genel Toplam",
            selectVaultBank: "Hedef Kasa / Banka Seçimi",
            balance: "Bakiye",
            noVaultFound: "Bu ödeme tipi için tanımlı kasa bulunamadı.",
            selectInstallment: "Taksit / Kredi Kartı Komisyonu Seçimi",
            deduction: "Kesinti",
            cancelGiveUp: "İptal / Vazgeç",
            totalDeductions: "Kesintiler Toplamı",
            confirmFinish: "ONAYLA VE BİTİR"
        },
        emustahsil: {
            errFarmer: "Üretici Seçimi Eksik",
            errFarmerDesc: "Makbuz düzenleyebilmek için lütfen Müstahsil (Çiftçi) seçiniz.",
            errEmpty: "Makbuz Boş",
            errEmptyDesc: "Lütfen en az bir kalem ekleyiniz.",
            successMsg: "E-Müstahsil Makbuzu Başarıyla İletildi",
            docNo: "Belge Numarası",
            errOccurred: "Hata Oluştu",
            errFailed: "Makbuz oluşturulamadı.",
            errConn: "Bağlantı Hatası",
            successTitle: "E-Müstahsil Makbuzu Düzenlendi",
            successDetail: "Belge başarıyla GİB portalına iletilmek üzere sıraya alındı.",
            btnNew: "YENİ MAKBUZ",
            btnPdf: "PDF OLARAK İNDİR",
            farmerSeller: "ÇİFTÇİ / MÜSTAHSİL (SATICI)",
            searchPlaceholder: "Üretici Ad Soyad veya TC/VKN Ara...",
            recentFarmers: "Son Kullanılan Üreticiler",
            changeFarmer: "Üreticiyi Değiştir",
            tcVkn: "TC/VKN",
            noAddress: "Adres bilgisi eksik.",
            docType: "Belge Tipi",
            docTypeLabel: "E-MÜSTAHSİL MAKBUZU",
            currency: "Döviz",
            cbrtRate: "TCMB Kuru",
            issueDate: "Düzenlenme Tarihi",
            branch: "Şube / Kasa",
            hq: "Merkez (Online)",
            thProduct: "Hizmet / Tarımsal Ürün Adı",
            thQty: "Miktar(Kg/Ad)",
            thPrice: "Birim Fiyat",
            thGv: "GV(%)",
            thSgk: "SGK(%)",
            thBorsa: "Borsa(%)",
            thMera: "Mera(%)",
            thGross: "Brüt Tutar",
            pHint: "Örn: Buğday, Arpa, Süt...",
            stockSearch: "🔍 Stok Arama",
            stockCards: "Stok Kartları",
            noResults: "Sonuç bulunamadı.",
            btnAddLine: "YENİ KALEM EKLE",
            noteLabel: "Makbuz Alt Notu / Açıklama",
            notePlaceholder: "Kesinti açıklamaları vs...",
            grossTotal: "Müstahsil Brüt Tutar",
            gvLabel: "(-) Gelir Vergisi (Stopaj)",
            sgkLabel: "(-) Bağ-Kur / SGK Kesintisi",
            borsaLabel: "(-) Borsa Tescil Ücreti",
            meraLabel: "(-) Mera Fonu",
            netPayableHint: "Net Üreticiye Ödenecek Tutar",
            netPayable: "ÇİFTÇİYE ÖDENECEK NET",
            sysEquiv: "Sistem (TL) Karşılığı",
            cashFlow: "Para Çıkış Yönü",
            paymentTransfer: "Üreticiye Ödeme Devri",
            btnCash: "Nakit Ödeme",
            btnTransfer: "Hesaba Havale",
            btnDeferred: "Cari Vade",
            btnDraft: "TASLAK OLARAK KAYDET",
            btnDraftShort: "TASLAK",
            btnCreate: "E-MÜSTAHSİL OLUŞTUR",
            btnWait: "BEKLEYİNİZ...",
            undefined: "Tanımsız",
            unspecified: "Belirtilmemiş"
        },
        esmm: {
            errCustomer: "Müşteri Seçimi Eksik",
            errCustomerDesc: "Makbuz düzenleyebilmek için lütfen alıcı seçiniz.",
            errEmpty: "Makbuz Boş",
            errEmptyDesc: "Lütfen en az bir hizmet ekleyiniz ve tutar giriniz.",
            successMsg: "E-SMM Başarıyla İletildi",
            errOccurred: "Hata Oluştu",
            errFailed: "Makbuz oluşturulamadı.",
            errConn: "Bağlantı Hatası",
            successTitle: "E-SMM Düzenlendi",
            successDetail: "Serbest Meslek Makbuzunuz başarıyla oluşturuldu ve GİB portalına iletilmek üzere kuyruğa eklendi.",
            btnNew: "YENİ E-SMM",
            btnPdf: "PDF OLARAK İNDİR",
            customerBuyer: "MÜŞTERİ / ALICI",
            searchPlaceholder: "Firma Ünvanı veya Müşteri Adı Ara...",
            recentCustomers: "Son Kullanılanlar",
            change: "Değiştir",
            vknTc: "VKN/TC",
            vkn: "VKN",
            noAddress: "Adres bilgisi eksik.",
            docType: "Belge Tipi",
            docTypeLabel: "E-SERBEST MESLEK MAKBUZU",
            currency: "Para Birimi",
            issueDate: "Düzenlenme",
            thServiceDesc: "Hizmet Açıklaması",
            thCalcType: "Hesap Tipi",
            thEnteredAmt: "Girilen Tutar",
            thGv: "GV (%)",
            thVat: "KDV (%)",
            thResult: "Çıkan Sonuç",
            pHint: "Örn: Haziran Ayı Mali Müşavirlik Hizmeti",
            grossMode: "Brütten",
            netMode: "Netten",
            btnAddLine: "YENİ HİZMET EKLE",
            formulaHint: "Serbest Meslek Makbuzunda Tahsil Edilen Net = Brüt + KDV - Stopaj Formülü Uygulanır",
            noteLabel: "Açıklama / IBAN Bilgileri",
            notePlaceholder: "Ödemenin yapılacağı hesap bilgileri vb...",
            grossFee: "Brüt Ücret (Hizmet Bedeli)",
            gvLabel: "(-) Gelir Vergisi (Stopaj)",
            vatCalc: "(+) KDV Hesaplanan",
            netCollected: "TAHSİL EDİLECEK NET",
            cashFlowIn: "Para Giriş Yönü",
            receiptCollection: "Makbuz Tahsilatı",
            btnCash: "Nakit",
            btnTransfer: "Havale",
            btnDeferred: "CariHesap",
            btnDraft: "TASLAK OLARAK KAYDET",
            btnDraftShort: "TASLAK",
            btnCreate: "E-SMM OLUŞTUR",
            btnWait: "BEKLEYİNİZ...",
            undefined: "Tanımsız",
            unspecified: "Belirtilmemiş"
        },
        cart: {
            empty: "Sepet Boş",
            emptyDesc: "Ürün okutarak veya arayarak ekleyin",
            product: "Ürün",
            unitPrice: "Birim Fiyat",
            qty: "Adet",
            subtotal: "Ara Toplam",
            delete: "Sil"
        },
        checkout: {
            summaryTitle: "SATIŞ ÖZETİ",
            customer: "Müşteri / Cari",
            required: "Zorunlu",
            select: "SEÇ",
            subtotal: "Ara Toplam",
            discount: "İndirim",
            vatExcl: "KDV Hariç Tutar",
            grandTotal: "GENEL TOPLAM",
            smartCashier: "Akıllı Kasiyer Kazanımları",
            paymentDiscount: "Ödeme İndirimi",
            earnedPoints: "Kazanç Puanı",
            freeItem: "BEDELSİZ",
            paymentMethod: "ÖDEME YÖNTEMİ",
            cashRegister: "PeşinKasa",
            cash: "Nakit",
            pos: "YazarKasa POS",
            paytr: "PayTR Link",
            transferEft: "Havale/EFT",
            transfer: "Havale",
            credit: "Cari Kredi",
            errSelectCustomer: "Müşteri seçilmeli",
            splitPayment: "Parçalı Tahsilat",
            suspend: "BEKLEMEYE AL",
            processing: "İŞLENİYOR...",
            createInvoice: "FATURA OLUŞTUR VE KES",
            completePayment: "ÖDEMEYİ TAMAMLA",
            offlineProcess: "OFFLINE İŞLEME AL"
        },
        menu: {
            workspace: "WORKSPACE",
            pos: "POS Terminal",
            kds: { parent: "Restoran & KDS", kitchen: "Mutfak Ekranı (KDS)", qmenu: "QR Sipariş & Menü", courier: "Kurye Operasyonu" },
            hub: { parent: "Periodya Hub", hub: "Hub Paneli", dispute: "Uyuşmazlık Çözüm Merkezi", cart: "Ağ Sepetim", orders: "Talepler & Siparişler", catalog: "B2B Katalog", finance: "Finans & Büyüme (Growth)", rfq: "RFQ & Sözleşmeler" },
            dealer: { parent: "Dealer Network", dealers: "Bayiler", catalog: "B2B Katalog", orders: "Sipariş Onayı", refunds: "İadeler", banners: "Banner Yönetimi", settings: "Ayarlar" },
            operations: "OPERASYONLAR",
            calendar: "Global Takvim",
            staffme: "Personel Portalı",
            tasks: { parent: "Görev Merkezi", tower: "Görev Kulesi" },
            signatures: { parent: "İmzalar", board: "İmza Panosu", envelopes: "Belge & Zarflar", inbox: "Gelen Talepler", completed: "Tamamlananlar" },
            recon: { parent: "Mutabakatlar", open: "Açık Mutabakatlar", all: "Tüm Mutabakatlar", disputes: "İtiraz Yönetimi" },
            accounting: "Finansal Yönetim",
            sales: { parent: "Satış Yönetimi", all: "Tüm Satışlar", radar: "Revenue Intelligence" },
            customers: { parent: "Cariler", customers: "Müşteriler", suppliers: "Tedarikçiler" },
            inventory: { parent: "Envanter", general: "Envanter Genel", warehouse: "Depo & Stoklar", mfg: "Üretim Kontrol Merkezi" },
            assets: { parent: "Varlık ve Demirbaş", list: "Demirbaş Listesi", assignments: "Zimmet Merkezi", mnx: "Bakım ve Masraflar" },
            service: { parent: "Servis Masası", dash: "Servis Dashboard", workOrders: "İş Emirleri", new: "Yeni İş Emri", calendar: "Servis Randevuları", tv: "Atölye Canlı TV", field: "Saha Planlama Panosu", fieldDash: "Servis Saha Paneli" },
            offers: "Teklifler",
            salesx: "SalesX Saha Paneli",
            hr: { parent: "İnsan Kaynakları", employees: "Personeller", perf: "Performans & Hedef" },
            campaign: { parent: "Kampanya Engine", dash: "Dashboard", new: "Yeni Kurgu", active: "Aktif Kampanyalar", scheduled: "Planlı Kampanyalar", perf: "Performans" },
            analytics: "ANALİTİK & YÖNETİM",
            reports: { parent: "İş Zekası", ceo: "CEO Tablosu", detail: "Detaylı Analiz" },
            fintech: "Fintech Tower",
            advisor: "Mali Müşavir",
            anomaly: "Anomaliler",
            system: "SİSTEM",
            import: "Gelişmiş İçe Aktar",
            integrations: "Entegrasyonlar",
            help: "Yardım Merkezi",
            billing: { parent: "Abonelik & Market", panel: "Abonelik Paneli", store: "Modül Mağazası" },
            settings: "Ayarlar"
        }
    },
    en: { 
        common: { save: "Save", cancel: "Cancel", welcome: "Welcome", search: "Search", delete: "Delete" },
        invoice: {
            successTitle: "E-Invoice Issued",
            successDesc: "Document successfully queued to GIB. E-mailed to the customer automatically.",
            btnNew: "NEW INVOICE",
            btnPdf: "DOWNLOAD PDF",
            buyerLabel: "CUSTOMER / INSTITUTION (BUYER)",
            searchCustomer: "Search Customer Title or Tax No...",
            recentCustomers: "Recent Customers",
            balance: "Balance",
            taxOffice: "Tax Off.",
            undefined: "Undefined",
            changeCustomer: "Change Customer",
            notSpecified: "Not specified",
            noAddress: "No registered address found. E-Archive invoice will be issued.",
            invoiceType: "Invoice Type",
            typeSales: "SALES INVOICE",
            typeReturn: "RETURN INVOICE",
            typeTevkifat: "WITHHOLDING INVOICE",
            typeIstisna: "EXEMPTION INVOICE",
            scenario: "Scenario",
            scenTicari: "COMMERCIAL INVOICE",
            scenTemel: "BASIC INVOICE",
            currency: "Currency",
            tcmbRate: "CBRT Rate",
            issueDate: "Issue Date",
            branch: "Branch / Register",
            branchMain: "HQ (Online)",
            addDispatch: "ADD WAYBILL / REFERENCE",
            dispatchNo: "Waybill Number",
            dispatchPlaceholder: "16-Digit Doc No",
            dispatchDate: "Waybill Date",
            thDesc: "Product / Service Description",
            thQty: "Qty",
            thPrice: "Unit Price",
            thDiscount: "Disc.(%)",
            thIsCode: "Exempt Code",
            thOtherTaxes: "Other Taxes",
            thVat: "VAT(%)",
            thTevkifat: "Withholding",
            thNet: "Net Total",
            itemSearch: "Description or product name...",
            stockSearchList: "🔍 Stock Search List",
            stockCards: "Stock Cards",
            stock: "Stock",
            vat: "VAT",
            notFound: "No results found.",
            otvNone: "No SCT",
            otvPercent: "Percentage SCT",
            otvAmount: "Fixed (Unit)",
            otvAmountLabel: "Amount/Rate:",
            tevkifatNone: "No Withholding",
            tevkifatFull: "10/10 (Full)",
            addLine: "ADD NEW LINE",
            noteLabel: "Invoice Footer Note",
            notePlaceholder: "Bank IBAN details, delivery note etc...",
            totSub: "Goods / Services Subtotal",
            totDisc: "Total Discount",
            totVat: "Calculated VAT",
            totOtv: "Calculated SCT",
            totOiv: "Calculated OIV",
            totTevkifat: "(-) Withheld VAT",
            totGrand: "TOTAL INCLUDING TAXES",
            totSys: "System Equivalent (TRY)",
            btnDraft: "SAVE AS DRAFT",
            btnDraftShort: "DRAFT",
            btnSend: "ISSUE E-INVOICE & SEND",
            btnWait: "PLEASE WAIT..."
        },
        adission: {
            successTitle: "E-Ticketing Printed",
            successDesc: "account ticket successfully forwarded to GIB and kitchen printer.",
            salon: "MAIN HALL (INDOOR)",
            teras: "TERRACE",
            bahce: "GARDEN",
            emptyCart: "No products in cart.",
            thProd: "Product",
            thQty: "Qty",
            thTotal: "Total",
            statusNew: "New",
            statusAvailable: "AVAILABLE",
            generalTotal: "Grand Total",
            btnPrinting: "PRINTING...",
            btnKitchen: "KITCHEN / BAR",
            btnClosing: "CLOSING...",
            btnCheckout: "CHECKOUT",
            standbyTitle: "Register Standby",
            standbyDesc: "Select a table from the left to process.",
            minutes: "min",
            unknown: "Unknown",
            emptyAdission: "Ticket Empty",
            errEmpty: "No items added to the table yet.",
            errKitchenEmpty: "No new items to send to the kitchen.",
            kitchenSuccess: "Sent to Kitchen",
            kitchenSuccessDesc: "new items sent to IP kitchen printer successfully."
        },
        terminal: {
            customer: "Customer",
            openAccount: "Open Account",
            liveRateOn: "Live Rate On",
            liveRateOff: "Live Rate Off",
            liveRateTooltip: "When active, product foreign exchange rates are instantly converted to TRY during sale.",
            coupon: "Coupon",
            points: "Points",
            ref: "Ref",
            pending: "Pending",
            quickSale: "Quick Sale",
            restoPos: "Resto-Pos",
            eInvoice: "E-Invoice",
            eMustahsil: "E-Producer",
            eSmm: "E-SMM",
            retailCustomer: "Retail Customer",
            customerSelection: "Customer Selection (F8)",
            searchPlaceholder: "Search...",
            escClose: "ESC - Close",
            pendingSales: "Pending Sales (F9)",
            noPendingSales: "No pending sales.",
            openBtn: "OPEN",
            deleteBtn: "DEL",
            productsText: "Product",
            suspendSale: "Suspend Sale",
            suspendLabelPlaceholder: "Label / Name (e.g. Table 5 or Customer Name)",
            btnSuspend: "Suspend",
            extrasDiscounts: "Extras & Discounts",
            cartDiscount: "Cart Discount",
            enterCode: "ENTER CODE",
            usePoints: "Use Points",
            available: "Available",
            orderNote: "Order Note / Reference",
            notePlaceholder: "Document, plate or table no...",
            confirm: "CONFIRM",
            completePayment: "Complete Payment",
            cartSubtotal: "Cart Subtotal",
            manualDiscount: "Manual Discount / Pts",
            autoRewards: "Auto Rewards",
            campaignDiscount: "Campaign Discount",
            pointsToEarn: "Points to Earn",
            freeInCart: "Free in Cart",
            grandTotal: "Grand Total",
            selectVaultBank: "Target Vault / Bank",
            balance: "Balance",
            noVaultFound: "No vault found for this payment type.",
            selectInstallment: "Select Installment / POS Commission",
            deduction: "Deduction",
            cancelGiveUp: "Cancel / Give Up",
            totalDeductions: "Total Deductions",
            confirmFinish: "CONFIRM & FINISH"
        },
        emustahsil: {
            errFarmer: "Missing Producer",
            errFarmerDesc: "Please select a Farmer (Producer) to issue a receipt.",
            errEmpty: "Receipt Empty",
            errEmptyDesc: "Please add at least one item.",
            successMsg: "E-Producer Receipt Sent Successfully",
            docNo: "Document Number",
            errOccurred: "An Error Occurred",
            errFailed: "Could not create receipt.",
            errConn: "Connection Error",
            successTitle: "E-Producer Receipt Created",
            successDetail: "Document successfully queued for GIB portal.",
            btnNew: "NEW RECEIPT",
            btnPdf: "DOWNLOAD PDF",
            farmerSeller: "FARMER / PRODUCER (SELLER)",
            searchPlaceholder: "Search Producer Name or TC/VKN...",
            recentFarmers: "Recent Producers",
            changeFarmer: "Change Producer",
            tcVkn: "TC/VKN",
            noAddress: "Address info missing.",
            docType: "Document Type",
            docTypeLabel: "E-PRODUCER RECEIPT",
            currency: "Currency",
            cbrtRate: "CBRT Rate",
            issueDate: "Issue Date",
            branch: "Branch / Register",
            hq: "Headquarters (Online)",
            thProduct: "Service / Agricultural Product Name",
            thQty: "Quantity(Kg/Pcs)",
            thPrice: "Unit Price",
            thGv: "IT(%)",
            thSgk: "SSI(%)",
            thBorsa: "Bourse(%)",
            thMera: "Pasture(%)",
            thGross: "Gross Total",
            pHint: "e.g. Wheat, Barley, Milk...",
            stockSearch: "🔍 Stock Search",
            stockCards: "Stock Cards",
            noResults: "No results found.",
            btnAddLine: "ADD NEW LINE",
            noteLabel: "Receipt Note / Description",
            notePlaceholder: "Deduction explanations etc...",
            grossTotal: "Producer Gross Total",
            gvLabel: "(-) Income Tax (Withholding)",
            sgkLabel: "(-) SGK / Social Security",
            borsaLabel: "(-) Bourse Registration Fee",
            meraLabel: "(-) Pasture Fund",
            netPayableHint: "Net Amount Payable to Producer",
            netPayable: "NET PAYABLE TO FARMER",
            sysEquiv: "System Equivalent (TRY)",
            cashFlow: "Cash Flow Direction",
            paymentTransfer: "Payment Transfer to Producer",
            btnCash: "Cash Payment",
            btnTransfer: "Bank Transfer",
            btnDeferred: "Current Account",
            btnDraft: "SAVE AS DRAFT",
            btnDraftShort: "DRAFT",
            btnCreate: "CREATE E-PRODUCER",
            btnWait: "PLEASE WAIT...",
            undefined: "Undefined",
            unspecified: "Unspecified"
        },
        esmm: {
            errCustomer: "Missing Customer",
            errCustomerDesc: "Please select a buyer to issue the receipt.",
            errEmpty: "Receipt Empty",
            errEmptyDesc: "Please add at least one service and enter an amount.",
            successMsg: "E-SMM Sent Successfully",
            errOccurred: "An Error Occurred",
            errFailed: "Could not create receipt.",
            errConn: "Connection Error",
            successTitle: "E-SMM Created",
            successDetail: "Your Self-Employment Receipt has been successfully created and queued for GIB portal.",
            btnNew: "NEW E-SMM",
            btnPdf: "DOWNLOAD PDF",
            customerBuyer: "CUSTOMER / BUYER",
            searchPlaceholder: "Search Company Title or Customer Name...",
            recentCustomers: "Recent Customers",
            change: "Change",
            vknTc: "TC/VKN",
            vkn: "VKN",
            noAddress: "Address info missing.",
            docType: "Document Type",
            docTypeLabel: "E-SELF EMPLOYMENT RECEIPT",
            currency: "Currency",
            issueDate: "Issue Date",
            thServiceDesc: "Service Description",
            thCalcType: "Calc Type",
            thEnteredAmt: "Entered Amount",
            thGv: "IT (%)",
            thVat: "VAT (%)",
            thResult: "Result",
            pHint: "e.g. June Financial Consultancy Service",
            grossMode: "From Gross",
            netMode: "From Net",
            btnAddLine: "ADD NEW SERVICE",
            formulaHint: "Formula: Net Collected = Gross + VAT - Withholding",
            noteLabel: "Note / IBAN Details",
            notePlaceholder: "Account info for payment etc...",
            grossFee: "Gross Fee",
            gvLabel: "(-) Income Tax (Withholding)",
            vatCalc: "(+) Calculated VAT",
            netCollected: "NET TO BE COLLECTED",
            cashFlowIn: "Cash Flow In",
            receiptCollection: "Receipt Collection",
            btnCash: "Cash",
            btnTransfer: "Transfer",
            btnDeferred: "Deferred",
            btnDraft: "SAVE AS DRAFT",
            btnDraftShort: "DRAFT",
            btnCreate: "CREATE E-SMM",
            btnWait: "PLEASE WAIT...",
            undefined: "Undefined",
            unspecified: "Unspecified"
        },
        cart: {
            empty: "Cart Empty",
            emptyDesc: "Scan or search to add a product",
            product: "Product",
            unitPrice: "Unit Price",
            qty: "Qty",
            subtotal: "Subtotal",
            delete: "Delete"
        },
        checkout: {
            summaryTitle: "SALES SUMMARY",
            customer: "Customer / Account",
            required: "Required",
            select: "SELECT",
            subtotal: "Subtotal",
            discount: "Discount",
            vatExcl: "VAT Excluded",
            grandTotal: "GRAND TOTAL",
            smartCashier: "Smart Cashier Rewards",
            paymentDiscount: "Payment Discount",
            earnedPoints: "Earned Points",
            freeItem: "FREE",
            paymentMethod: "PAYMENT METHOD",
            cashRegister: "Cash Register",
            cash: "Cash",
            pos: "POS Terminal",
            paytr: "PayTR Link",
            transferEft: "Transfer/EFT",
            transfer: "Transfer",
            credit: "Credit Account",
            errSelectCustomer: "Customer must be selected",
            splitPayment: "Split Payment",
            suspend: "SUSPEND ORDER",
            processing: "PROCESSING...",
            createInvoice: "CREATE INVOICE",
            completePayment: "COMPLETE PAYMENT",
            offlineProcess: "PROCESS OFFLINE"
        },
        menu: {
            workspace: "WORKSPACE",
            pos: "POS Terminal",
            kds: { parent: "Restaurant & KDS", kitchen: "Kitchen Display (KDS)", qmenu: "QR Ordering & Menu", courier: "Courier Operations" },
            hub: { parent: "Periodya Hub", hub: "Hub Dashboard", dispute: "Dispute Resolution Center", cart: "Network Cart", orders: "Requests & Orders", catalog: "B2B Catalog", finance: "Finance & Growth", rfq: "RFQs & Contracts" },
            dealer: { parent: "Dealer Network", dealers: "Dealers", catalog: "B2B Catalog", orders: "Order Approvals", refunds: "Refunds", banners: "Banner Management", settings: "Settings" },
            operations: "OPERATIONS",
            calendar: "Global Calendar",
            staffme: "Staff Portal",
            tasks: { parent: "Task Center", tower: "Task Tower" },
            signatures: { parent: "Signatures", board: "Signature Board", envelopes: "Documents & Envelopes", inbox: "Incoming Requests", completed: "Completed" },
            recon: { parent: "Reconciliation", open: "Open Reconciliations", all: "All Reconciliations", disputes: "Dispute Management" },
            accounting: "Financial Management",
            sales: { parent: "Sales Management", all: "All Sales", radar: "Revenue Intelligence" },
            customers: { parent: "Current Accounts", customers: "Customers", suppliers: "Suppliers" },
            inventory: { parent: "Inventory", general: "Inventory Overview", warehouse: "Warehouses & Stock", mfg: "Manufacturing Control Center" },
            assets: { parent: "Assets & Fixtures", list: "Asset List", assignments: "Assignment Center", mnx: "Maintenance & Expenses" },
            service: { parent: "Service Desk", dash: "Service Dashboard", workOrders: "Work Orders", new: "New Work Order", calendar: "Service Appointments", tv: "Workshop Live TV", field: "Field Planning Board", fieldDash: "Field Service Panel" },
            offers: "Quotes",
            salesx: "SalesX Field Panel",
            hr: { parent: "Human Resources", employees: "Employees", perf: "Performance & Targets" },
            campaign: { parent: "Campaign Engine", dash: "Dashboard", new: "New Setup", active: "Active Campaigns", scheduled: "Scheduled Campaigns", perf: "Performance Analytics" },
            analytics: "ANALYTICS & MANAGEMENT",
            reports: { parent: "Business Intelligence", ceo: "CEO Dashboard", detail: "Detailed Analysis" },
            fintech: "Fintech Tower",
            advisor: "Financial Advisor",
            anomaly: "Anomalies",
            system: "SYSTEM",
            import: "Advanced Import",
            integrations: "Integrations",
            help: "Help Center",
            billing: { parent: "Billing & Market", panel: "Billing Dashboard", store: "App Store" },
            settings: "Settings"
        }
    },
    de: { 
        common: { save: "Speichern", cancel: "Abbrechen", welcome: "Willkommen", search: "Suche", delete: "Löschen" },
        invoice: {
            successTitle: "E-Rechnung erstellt",
            successDesc: "Dokument erfolgreich an GIB gesendet. Automatisch an den Kunden per E-Mail gesendet.",
            btnNew: "NEUE RECHNUNG",
            btnPdf: "PDF HERUNTERLADEN",
            buyerLabel: "KUNDE / INSTITUTION (KÄUFER)",
            searchCustomer: "Kundenname oder Steuernummer suchen...",
            recentCustomers: "Kürzlich verwendete Kunden",
            balance: "Saldo",
            taxOffice: "Finanzamt",
            undefined: "Undefiniert",
            changeCustomer: "Kunde wechseln",
            notSpecified: "Nicht angegeben",
            noAddress: "Keine Adresse gefunden. E-Archiv-Rechnung wird erstellt.",
            invoiceType: "Rechnungsart",
            typeSales: "VERKAUFSRECHNUNG",
            typeReturn: "RÜCKGABERECHNUNG",
            typeTevkifat: "QUELLENSTEUERRECHNUNG",
            typeIstisna: "BEFREIUNGSRECHNUNG",
            scenario: "Szenario",
            scenTicari: "HANDELSRECHNUNG",
            scenTemel: "BASISRECHNUNG",
            currency: "Währung",
            tcmbRate: "CBRT Kurs",
            issueDate: "Ausstellungsdatum",
            branch: "Filiale / Kasse",
            branchMain: "Zentrale (Online)",
            addDispatch: "LIEFERSCHEIN / REFERENZ HINZUFÜGEN",
            dispatchNo: "Lieferscheinnummer",
            dispatchPlaceholder: "16-stellige Dokument-Nr",
            dispatchDate: "Lieferscheindatum",
            thDesc: "Produkt / Leistungsbeschreibung",
            thQty: "Menge",
            thPrice: "Einzelpreis",
            thDiscount: "Rabatt(%)",
            thIsCode: "Befreiungscode",
            thOtherTaxes: "Andere Steuern",
            thVat: "MwSt(%)",
            thTevkifat: "Quellensteuer",
            thNet: "Nettobetrag",
            itemSearch: "Beschreibung oder Produktname...",
            stockSearchList: "🔍 Bestandssuche",
            stockCards: "Lagerkarten",
            stock: "Bestand",
            vat: "MwSt",
            notFound: "Keine Ergebnisse gefunden.",
            otvNone: "Keine SCT",
            otvPercent: "Prozentuale SCT",
            otvAmount: "Fest (Einheit)",
            otvAmountLabel: "Betrag/Rate:",
            tevkifatNone: "Ohne Abzug",
            tevkifatFull: "10/10 (Voll)",
            addLine: "NEUE ZEILE",
            noteLabel: "Rechnungsfußnote",
            notePlaceholder: "Bank-IBAN-Details, Lieferschein usw...",
            totSub: "Waren / Dienstleistungen Zwischensumme",
            totDisc: "Gesamtrabatt",
            totVat: "Berechnete MwSt",
            totOtv: "Berechnete SCT",
            totOiv: "Berechnete OIV",
            totTevkifat: "(-) Einbehaltene MwSt",
            totGrand: "GESAMTSUMME INKLUSIVE STEUERN",
            totSys: "Systemäquivalent (TRY)",
            btnDraft: "ALS ENTWURF SPEICHERN",
            btnDraftShort: "ENTWURF",
            btnSend: "E-RECHNUNG ERSTELLEN & SENDEN",
            btnWait: "BITTE WARTEN..."
        },
        adission: {
            successTitle: "E-Bon gedruckt",
            successDesc: "Konto-Bon erfolgreich an GIB und Küchendrucker übermittelt.",
            salon: "HAUPTSAAL (INNEN)",
            teras: "TERRASSE",
            bahce: "GARTEN",
            emptyCart: "Keine Produkte im Warenkorb.",
            thProd: "Produkt",
            thQty: "Menge",
            thTotal: "Gesamt",
            statusNew: "Neu",
            statusAvailable: "VERFÜGBAR",
            generalTotal: "Gesamtsumme",
            btnPrinting: "WIRD GEDRUCKT...",
            btnKitchen: "KÜCHE / BAR",
            btnClosing: "WIRD GESCHLOSSEN...",
            btnCheckout: "ABRECHNEN",
            standbyTitle: "Kasse in Bereitschaft",
            standbyDesc: "Wählen Sie links einen Tisch zur Bearbeitung.",
            minutes: "min",
            unknown: "Unbekannt",
            emptyAdission: "Tisch Ist Leer",
            errEmpty: "Es wurden noch keine Artikel zum Tisch hinzugefügt.",
            errKitchenEmpty: "Keine neuen Artikel für die Küche.",
            kitchenSuccess: "An Küche gesendet",
            kitchenSuccessDesc: "neue Artikel erfolgreich an den IP-Küchendrucker gesendet."
        },
        terminal: {
            customer: "Kunde",
            openAccount: "Offenes Konto",
            liveRateOn: "Live-Kurse Ein",
            liveRateOff: "Live-Kurse Aus",
            liveRateTooltip: "Wenn aktiv, werden Fremdwährungen während des Verkaufs sofort in TRY umgerechnet.",
            coupon: "Gutschein",
            points: "Punkte",
            ref: "Ref",
            pending: "Ausstehend",
            quickSale: "Schnellverkauf",
            restoPos: "Resto-Pos",
            eInvoice: "E-Rechnung",
            eMustahsil: "E-Erzeuger",
            eSmm: "E-SMM",
            retailCustomer: "Einzelhandelskunde",
            customerSelection: "Kundenauswahl (F8)",
            searchPlaceholder: "Suchen...",
            escClose: "ESC - Schließen",
            pendingSales: "Ausstehende Verkäufe (F9)",
            noPendingSales: "Keine ausstehenden Verkäufe.",
            openBtn: "ÖFFNEN",
            deleteBtn: "LÖS",
            productsText: "Produkt",
            suspendSale: "Verkauf paussieren",
            suspendLabelPlaceholder: "Etikett / Name (z.B. Tisch 5 oder Kundenname)",
            btnSuspend: "Pausieren",
            extrasDiscounts: "Extras & Rabatte",
            cartDiscount: "Warenkorbrabatt",
            enterCode: "CODE EINGEBEN",
            usePoints: "Punkte Verwenden",
            available: "Verfügbar",
            orderNote: "Bestellnotiz / Referenz",
            notePlaceholder: "Dokument, Kennzeichen oder Tischnummer...",
            confirm: "BESTÄTIGEN",
            completePayment: "Zahlung Abschließen",
            cartSubtotal: "Warenkorb-Zwischensumme",
            manualDiscount: "Manueller Rabatt / Pkt",
            autoRewards: "Auto-Belohnungen",
            campaignDiscount: "Kampagnenrabatt",
            pointsToEarn: "Zu verdienende Punkte",
            freeInCart: "Kostenlos im Warenkorb",
            grandTotal: "Gesamtsumme",
            selectVaultBank: "Zielkasse / Bank",
            balance: "Saldo",
            noVaultFound: "Keine Kasse für diese Zahlungsart gefunden.",
            selectInstallment: "Ratenzahlung / POS-Provision Wählen",
            deduction: "Abzug",
            cancelGiveUp: "Abbrechen",
            totalDeductions: "Gesamtabzüge",
            confirmFinish: "BESTÄTIGEN & ABSCHLIESSEN"
        },
        emustahsil: {
            errFarmer: "Erzeuger fehlt",
            errFarmerDesc: "Bitte wählen Sie einen Landwirt (Erzeuger) aus, um eine Quittung auszustellen.",
            errEmpty: "Quittung leer",
            errEmptyDesc: "Bitte fügen Sie mindestens einen Artikel hinzu.",
            successMsg: "E-Erzeugerquittung erfolgreich gesendet",
            docNo: "Dokumentnummer",
            errOccurred: "Ein Fehler ist aufgetreten",
            errFailed: "Quittung konnte nicht erstellt werden.",
            errConn: "Verbindungsfehler",
            successTitle: "E-Erzeugerquittung erstellt",
            successDetail: "Dokument erfolgreich für das GIB-Portal in die Warteschlange gestellt.",
            btnNew: "NEUE QUITTUNG",
            btnPdf: "PDF HERUNTERLADEN",
            farmerSeller: "LANDWIRT / ERZEUGER (VERKÄUFER)",
            searchPlaceholder: "Erzeugername oder TC/VKN suchen...",
            recentFarmers: "Kürzlich verwendete Erzeuger",
            changeFarmer: "Erzeuger ändern",
            tcVkn: "TC/VKN",
            noAddress: "Adressinfo fehlt.",
            docType: "Dokumenttyp",
            docTypeLabel: "E-ERZEUGERQUITTUNG",
            currency: "Währung",
            cbrtRate: "CBRT-Kurs",
            issueDate: "Ausstellungsdatum",
            branch: "Filiale / Kasse",
            hq: "Zentrale (Online)",
            thProduct: "Dienstleistung / Landwirtschaftsprodukt",
            thQty: "Menge(Kg/Stk)",
            thPrice: "Einzelpreis",
            thGv: "ESt(%)",
            thSgk: "SV(%)",
            thBorsa: "Börse(%)",
            thMera: "Weide(%)",
            thGross: "Bruttosumme",
            pHint: "z.B. Weizen, Gerste, Milch...",
            stockSearch: "🔍 Bestandssuche",
            stockCards: "Lagerkarten",
            noResults: "Keine Ergebnisse gefunden.",
            btnAddLine: "NEUE ZEILE HINZUFÜGEN",
            noteLabel: "Quittungsnotiz / Beschreibung",
            notePlaceholder: "Abzugserklärungen usw...",
            grossTotal: "Erzeuger-Bruttosumme",
            gvLabel: "(-) Einkommensteuer",
            sgkLabel: "(-) SGK / Sozialversicherung",
            borsaLabel: "(-) Börsenregistrierungsgebühr",
            meraLabel: "(-) Weidefonds",
            netPayableHint: "An Erzeuger zu zahlender Nettobetrag",
            netPayable: "AN LANDWIRT ZU ZAHLEN (NETTO)",
            sysEquiv: "Systemäquivalent (TRY)",
            cashFlow: "Geldflussrichtung",
            paymentTransfer: "Zahlungsüberweisung an Erzeuger",
            btnCash: "Barzahlung",
            btnTransfer: "Banküberweisung",
            btnDeferred: "Kontokorrent",
            btnDraft: "ALS ENTWURF SPEICHERN",
            btnDraftShort: "ENTWURF",
            btnCreate: "E-ERZEUGER ERSTELLEN",
            btnWait: "BITTE WARTEN...",
            undefined: "Undefiniert",
            unspecified: "Nicht angegeben"
        },
        esmm: {
            errCustomer: "Kunde fehlt",
            errCustomerDesc: "Bitte wählen Sie einen Käufer zur Ausstellung der Quittung aus.",
            errEmpty: "Quittung leer",
            errEmptyDesc: "Bitte fügen Sie mindestens eine Dienstleistung hinzu und geben Sie einen Betrag ein.",
            successMsg: "E-SMM erfolgreich gesendet",
            errOccurred: "Ein Fehler ist aufgetreten",
            errFailed: "Quittung konnte nicht erstellt werden.",
            errConn: "Verbindungsfehler",
            successTitle: "E-SMM Erstellt",
            successDetail: "Ihre Freiberufler-Quittung wurde erfolgreich erstellt und für das GIB-Portal in die Warteschlange gestellt.",
            btnNew: "NEUE E-SMM",
            btnPdf: "PDF HERUNTERLADEN",
            customerBuyer: "KUNDE / KÄUFER",
            searchPlaceholder: "Firmenname oder Kundenname suchen...",
            recentCustomers: "Kürzlich verwendete",
            change: "Ändern",
            vknTc: "TC/VKN",
            vkn: "VKN",
            noAddress: "Adressinfo fehlt.",
            docType: "Dokumenttyp",
            docTypeLabel: "E-FREIBERUFLER-QUITTUNG",
            currency: "Währung",
            issueDate: "Ausstellungsdatum",
            thServiceDesc: "Dienstleistungsbeschreibung",
            thCalcType: "Berechnungstyp",
            thEnteredAmt: "Eingegebener Betrag",
            thGv: "ESt (%)",
            thVat: "MwSt (%)",
            thResult: "Ergebnis",
            pHint: "z.B. Finanzberatung Juni",
            grossMode: "Vom Brutto",
            netMode: "Vom Netto",
            btnAddLine: "NEUE DIENSTLEISTUNG HINZUFÜGEN",
            formulaHint: "Formel: Netto erzielt = Brutto + MwSt - Quellensteuer",
            noteLabel: "Notiz / IBAN-Details",
            notePlaceholder: "Kontoinformationen für die Zahlung usw.",
            grossFee: "Bruttogebühr",
            gvLabel: "(-) Einkommensteuer",
            vatCalc: "(+) Berechnete MwSt",
            netCollected: "EINZUZIEHENDES NETTO",
            cashFlowIn: "Geldeingang",
            receiptCollection: "Quittungseinzug",
            btnCash: "Bar",
            btnTransfer: "Überweisung",
            btnDeferred: "Aufgeschoben",
            btnDraft: "ALS ENTWURF SPEICHERN",
            btnDraftShort: "ENTWURF",
            btnCreate: "E-SMM ERSTELLEN",
            btnWait: "BITTE WARTEN...",
            undefined: "Undefiniert",
            unspecified: "Nicht angegeben"
        },
        cart: {
            empty: "Warenkorb leer",
            emptyDesc: "Scannen oder suchen Sie, um ein Produkt hinzuzufügen",
            product: "Produkt",
            unitPrice: "Einzelpreis",
            qty: "Menge",
            subtotal: "Zwischensumme",
            delete: "Löschen"
        },
        checkout: {
            summaryTitle: "VERKAUFSÜBERSICHT",
            customer: "Kunde / Konto",
            required: "Erforderlich",
            select: "AUSWÄHLEN",
            subtotal: "Zwischensumme",
            discount: "Rabatt",
            vatExcl: "Exkl. MwSt",
            grandTotal: "GESAMTSUMME",
            smartCashier: "Smart Cashier Belohnungen",
            paymentDiscount: "Zahlungsrabatt",
            earnedPoints: "Verdiente Punkte",
            freeItem: "KOSTENLOS",
            paymentMethod: "ZAHLUNGSMETHODE",
            cashRegister: "Kasse",
            cash: "Barzahlung",
            pos: "Kartenzahlung (POS)",
            paytr: "PayTR-Link",
            transferEft: "Überweisung/EFT",
            transfer: "Überweisung",
            credit: "Kundenkredit",
            errSelectCustomer: "Kunde muss ausgewählt werden",
            splitPayment: "Teilzahlung",
            suspend: "BESTELLUNG PAUSIEREN",
            processing: "WIRD BEARBEITET...",
            createInvoice: "RECHNUNG ERSTELLEN",
            completePayment: "ZAHLUNG ABSCHLIESSEN",
            offlineProcess: "OFFLINE BEARBEITEN"
        },
        menu: {
            workspace: "ARBEITSBEREICH",
            pos: "Kassensystem (POS)",
            kds: { parent: "Gastro & KDS", kitchen: "Küchendisplay (KDS)", qmenu: "QR Bestellungen & Menü", courier: "Kurier-Betrieb" },
            hub: { parent: "Periodya Hub", hub: "Hub-Dashboard", dispute: "Streitbeilegungszentrum", cart: "Netzwerk-Warenkorb", orders: "Anfragen & Bestellungen", catalog: "B2B-Katalog", finance: "Finanzen & Wachstum", rfq: "Ausschreibungen & Verträge" },
            dealer: { parent: "Händlernetzwerk", dealers: "Händler", catalog: "B2B-Katalog", orders: "Bestellgenehmigungen", refunds: "Rückerstattungen", banners: "Banner-Management", settings: "Einstellungen" },
            operations: "OPERATIONEN",
            calendar: "Globaler Kalender",
            staffme: "Mitarbeiter-Portal",
            tasks: { parent: "Aufgabenzentrum", tower: "Aufgaben-Turm" },
            signatures: { parent: "Unterschriften", board: "Signatur-Board", envelopes: "Dokumente & Umschläge", inbox: "Eingehende Anfragen", completed: "Abgeschlossen" },
            recon: { parent: "Abstimmung", open: "Offene Abstimmungen", all: "Alle Abstimmungen", disputes: "Konfliktmanagement" },
            accounting: "Finanzmanagement",
            sales: { parent: "Vertriebsmanagement", all: "Alle Verkäufe", radar: "Umsatz-Intelligenz" },
            customers: { parent: "Kunden & Lieferanten", customers: "Kunden", suppliers: "Lieferanten" },
            inventory: { parent: "Inventar", general: "Inventarübersicht", warehouse: "Lager & Bestand", mfg: "Produktions­kontrollzentrum" },
            assets: { parent: "Anlagen & Ausstattung", list: "Anlagenliste", assignments: "Zuweisungszentrum", mnx: "Wartung & Ausgaben" },
            service: { parent: "Service Desk", dash: "Service-Dashboard", workOrders: "Arbeitsaufträge", new: "Neuer Arbeitsauftrag", calendar: "Service-Termine", tv: "Werkstatt Live-TV", field: "Einsatzplanung", fieldDash: "Service-Einsatzpanel" },
            offers: "Angebote",
            salesx: "SalesX Außendienst",
            hr: { parent: "Personalwesen", employees: "Mitarbeiter", perf: "Leistung & Ziele" },
            campaign: { parent: "Kampagnen-Engine", dash: "Dashboard", new: "Neues Setup", active: "Aktive Kampagnen", scheduled: "Geplante Kampagnen", perf: "Leistungsanalysen" },
            analytics: "ANALYTIK & MANAGEMENT",
            reports: { parent: "Business Intelligence", ceo: "CEO-Dashboard", detail: "Detaillierte Analyse" },
            fintech: "Fintech-Turm",
            advisor: "Steuerberater",
            anomaly: "Anomalien",
            system: "SYSTEM",
            import: "Erweiterter Import",
            integrations: "Integrationen",
            help: "Hilfe-Center",
            billing: { parent: "Abrechnung & Store", panel: "Abrechnungs-Dashboard", store: "App-Store" },
            settings: "Einstellungen"
        }
    }
};

type Language = "tr" | "en" | "de";

interface LanguageContextProps {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string, variables?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextProps>({
    language: "tr",
    setLanguage: () => {},
    t: (key) => key,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [language, setLanguageState] = useState<Language>("tr");
    const [dictionaries, setDictionaries] = useState<Record<string, any>>(defaultDictionaries);

    useEffect(() => {
        // Load user's preferred language from local storage
        const savedLang = localStorage.getItem("periodya_lang") as Language;
        if (savedLang && ["tr", "en", "de"].includes(savedLang)) {
            setLanguageState(savedLang);
        }

        // Future: Fetch extended dictionaries from a server or dynamic imports here
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem("periodya_lang", lang);
        // Optionally reload or sync state to server
    };

    const t = (key: string, variables?: Record<string, any>): string => {
        const keys = key.split(".");
        let value = dictionaries[language];

        for (const k of keys) {
            if (value && typeof value === 'object') {
                value = value[k];
            } else {
                value = undefined;
                break;
            }
        }

        // If string not found in target language, fallback to TR or just return the key
        if (value === undefined) {
             let trValue = dictionaries["tr"];
             for (const k of keys) {
                if (trValue && typeof trValue === 'object') trValue = trValue[k];
                else { trValue = undefined; break; }
             }
             value = trValue !== undefined ? trValue : key;
        }

        if (typeof value !== 'string') return key;

        // Replace variables e.g. {name} -> variables.name
        if (variables) {
            return value.replace(/\{(\w+)\}/g, (_, vKey) => {
                return variables[vKey] !== undefined ? variables[vKey] : `{${vKey}}`;
            });
        }

        return value;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
