"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

// Fallback empty dictionaries if fetch fails or is incomplete
const defaultDictionaries: Record<string, any> = {
    tr: { 
        common: { save: "Kaydet", cancel: "İptal", welcome: "Hoş geldiniz", search: "Ara", delete: "Sil" },
        invoice: {
            successTitle: "E-Fatura Kesildi",
            successDesc: "Belge GİB kuyruğuna başarıyla eklendi. Müşteriye e-posta olarak otomatik iletilmiştir.",
            btnNew: "YENİ FATURA",
            btnPdf: "PDF OLARAK İNDİR",
            buyerLabel: "SAYIN / KURUM (ALICI)",
            searchCustomer: "Fatura Kesilecek Cari Ünvan veya Vergi No...",
            recentCustomers: "Son Kullanılan Cariler",
            balance: "Bakiye",
            taxOffice: "Vergi D.",
            undefined: "Tanımsız",
            changeCustomer: "Cariyi Değiştir",
            notSpecified: "Belirtilmemiş",
            noAddress: "Kayıtlı açık adres bulunamadı. Fatura E-Arşiv olarak kesilecektir.",
            invoiceType: "Fatura Tipi",
            typeSales: "SATIŞ FATURASI",
            typeReturn: "İADE FATURASI",
            typeTevkifat: "TEVKİFATLI FATURA",
            typeIstisna: "İSTİSNA FATURASI",
            scenario: "Senaryo",
            scenTicari: "TİCARİ FATURA",
            scenTemel: "TEMEL FATURA",
            currency: "Döviz",
            tcmbRate: "TCMB Kuru",
            issueDate: "Düzenlenme Tarihi",
            branch: "Şube / Kasa",
            branchMain: "Merkez (Online)",
            addDispatch: "E-İRSALİYE / REFERANS EKLE",
            dispatchNo: "İrsaliye Numarası",
            dispatchPlaceholder: "16 Haneli Belge No",
            dispatchDate: "İrsaliye Tarihi",
            thDesc: "Ürün / Hizmet Açıklaması",
            thQty: "Miktar",
            thPrice: "Birim Fiyat",
            thDiscount: "İsk.(%)",
            thIsCode: "İstisna Kodu",
            thOtherTaxes: "Diğer Vergiler",
            thVat: "KDV(%)",
            thTevkifat: "Tevkifat",
            thNet: "Net Tutar",
            itemSearch: "Açıklama veya ürün adı...",
            stockSearchList: "🔍 Stok Arama Listesi",
            stockCards: "Stok Kartları",
            stock: "Stok",
            vat: "KDV",
            notFound: "Sonuç bulunamadı.",
            otvNone: "Ö.T.V Yok",
            otvPercent: "Yüzdesel ÖTV",
            otvAmount: "Maktu (Birim)",
            otvAmountLabel: "Tutar/Oran:",
            tevkifatNone: "Tevkifatsız",
            tevkifatFull: "10/10 (Tam)",
            addLine: "YENİ SATIR EKLE",
            noteLabel: "Fatura Alt Notu",
            notePlaceholder: "Banka IBAN bilgileri, teslimat notu vb...",
            totSub: "Mal / Hizmet Toplam Tutar",
            totDisc: "Toplam İskonto",
            totVat: "Hesaplanan KDV",
            totOtv: "Hesaplanan ÖTV",
            totOiv: "Hesaplanan OİV",
            totTevkifat: "(-) Tevkif Edilen KDV",
            totGrand: "VERGİLER DAHİL TOPLAM",
            totSys: "Sistem (TL) Karşılığı",
            btnDraft: "TASLAK OLARAK KAYDET",
            btnDraftShort: "TASLAK",
            btnSend: "E-FATURALAŞTIR VE GÖNDER",
            btnWait: "BEKLEYİNİZ..."
        },
        adission: {
            successTitle: "E-Adisyon Yazdırıldı",
            successDesc: "hesabına ait elektronik adisyon başarıyla GİB'e iletildi ve mutfak fişi çıkarılıyor.",
            salon: "SALON (İÇ MEKAN)",
            teras: "TERAS",
            bahce: "BAHÇE",
            emptyCart: "Sepette ürün yok.",
            thProd: "Ürün",
            thQty: "Miktar",
            thTotal: "Tutar",
            statusNew: "Yeni",
            statusAvailable: "UYGUN",
            generalTotal: "Genel Toplam",
            btnPrinting: "YAZDIRILIYOR...",
            btnKitchen: "MUTFAK / BAR",
            btnClosing: "KAPATILIYOR...",
            btnCheckout: "HESABI KAPAT",
            standbyTitle: "Kasa Beklemede",
            standbyDesc: "İşlem yapmak için sol taraftan bir masa seçin.",
            minutes: "dk",
            unknown: "Belirsiz",
            emptyAdission: "Adisyon Boş",
            errEmpty: "Masaya henüz ürün eklenmemiş.",
            errKitchenEmpty: "Mutfağa iletilecek yeni bir ürün yok.",
            kitchenSuccess: "Mutfağa İletildi",
            kitchenSuccessDesc: "yeni ürün/istek IP mutfak yazıcısına başarıyla gönderildi."
        },
        terminal: {
            customer: "Cari",
            openAccount: "Açık Hesap",
            liveRateOn: "Canlı Kur Açık",
            liveRateOff: "Canlı Kur Kapalı",
            liveRateTooltip: "Aktif olduğunda ürünlerin döviz kurları anlık olarak TL'ye çevrilerek satışı yapılır.",
            coupon: "Kupon",
            points: "Puan",
            ref: "Ref",
            pending: "Bekleyen",
            quickSale: "Hızlı Satış",
            restoPos: "Resto-Pos",
            eInvoice: "E-Fatura",
            eMustahsil: "E-Müstahsil",
            eSmm: "E-SMM",
            retailCustomer: "Perakende Müşteri",
            customerSelection: "Müşteri Seçimi (F8)",
            searchPlaceholder: "Arama...",
            escClose: "ESC - Kapat",
            pendingSales: "Bekleyen Satışlar (F9)",
            noPendingSales: "Bekleyen satış yok.",
            openBtn: "AÇ",
            deleteBtn: "SİL",
            productsText: "Ürün",
            suspendSale: "Satışı Beklemeye Al",
            suspendLabelPlaceholder: "Etiket / İsim (Örn: Masa 5 veya Müşteri Adı)",
            btnSuspend: "Beklemeye Al",
            extrasDiscounts: "Ekstra & İndirimler",
            cartDiscount: "Sepet İndirimi",
            enterCode: "KOD GİRİN",
            usePoints: "Puan Kullan",
            available: "Kullanılabilir",
            orderNote: "Sipariş Notu / Referans",
            notePlaceholder: "Belge, plaka veya masa no...",
            confirm: "ONAYLA",
            completePayment: "Ödemeyi Tamamla",
            cartSubtotal: "Sepet Ara Toplam",
            manualDiscount: "Manuel İndirim / Puan",
            autoRewards: "Otomatik Kazanımlar",
            campaignDiscount: "Kampanya İndirimi",
            pointsToEarn: "Kazanılacak Parapuan",
            freeInCart: "Bedelsiz Sepette",
            grandTotal: "Genel Toplam",
            selectVaultBank: "Hedef Kasa / Banka Seçimi",
            balance: "Bakiye",
            noVaultFound: "Bu ödeme tipi için tanımlı kasa bulunamadı.",
            selectInstallment: "Taksit / Kredi Kartı Komisyonu Seçimi",
            deduction: "Kesinti",
            cancelGiveUp: "İptal / Vazgeç",
            processing: "İŞLENİYOR...",
            confirmFinish: "ONAYLA VE BİTİR"
        },
        menu: {
            workspace: "WORKSPACE",
            pos: "POS Terminal",
            kds: { parent: "Restoran & KDS", kitchen: "Mutfak Ekranı (KDS)", qmenu: "QR Sipariş & Menü", courier: "Kurye Operasyonu" },
            hub: { parent: "Periodya Hub", hub: "Hub Paneli", dispute: "Uyuşmazlık Çözüm Merkezi", cart: "Ağ Sepetim", orders: "Talepler & Siparişler", catalog: "B2B Katalog", finance: "Finans & Büyüme (Growth)", rfq: "RFQ & Sözleşmeler" },
            dealer: { parent: "Dealer Network", dealers: "Bayiler", catalog: "B2B Katalog", orders: "Sipariş Onayı", refunds: "İadeler", banners: "Banner Yönetimi", settings: "Ayarlar" },
            operations: "OPERASYONLAR",
            calendar: "Global Takvim",
            staffme: "Personel Portalı",
            tasks: { parent: "Görev Merkezi", tower: "Görev Kulesi" },
            signatures: { parent: "İmzalar", board: "İmza Panosu", envelopes: "Belge & Zarflar", inbox: "Gelen Talepler", completed: "Tamamlananlar" },
            recon: { parent: "Mutabakatlar", open: "Açık Mutabakatlar", all: "Tüm Mutabakatlar", disputes: "İtiraz Yönetimi" },
            accounting: "Finansal Yönetim",
            sales: { parent: "Satış Yönetimi", all: "Tüm Satışlar", radar: "Revenue Intelligence" },
            customers: { parent: "Cariler", customers: "Müşteriler", suppliers: "Tedarikçiler" },
            inventory: { parent: "Envanter", general: "Envanter Genel", warehouse: "Depo & Stoklar", mfg: "Üretim Kontrol Merkezi" },
            assets: { parent: "Varlık ve Demirbaş", list: "Demirbaş Listesi", assignments: "Zimmet Merkezi", mnx: "Bakım ve Masraflar" },
            service: { parent: "Servis Masası", dash: "Servis Dashboard", workOrders: "İş Emirleri", new: "Yeni İş Emri", calendar: "Servis Randevuları", tv: "Atölye Canlı TV", field: "Saha Planlama Panosu", fieldDash: "Servis Saha Paneli" },
            offers: "Teklifler",
            salesx: "SalesX Saha Paneli",
            hr: { parent: "İnsan Kaynakları", employees: "Personeller", perf: "Performans & Hedef" },
            campaign: { parent: "Kampanya Engine", dash: "Dashboard", new: "Yeni Kurgu", active: "Aktif Kampanyalar", scheduled: "Planlı Kampanyalar", perf: "Performans" },
            analytics: "ANALİTİK & YÖNETİM",
            reports: { parent: "İş Zekası", ceo: "CEO Tablosu", detail: "Detaylı Analiz" },
            fintech: "Fintech Tower",
            advisor: "Mali Müşavir",
            anomaly: "Anomaliler",
            system: "SİSTEM",
            import: "Gelişmiş İçe Aktar",
            integrations: "Entegrasyonlar",
            help: "Yardım Merkezi",
            billing: { parent: "Abonelik & Market", panel: "Abonelik Paneli", store: "Modül Mağazası" },
            settings: "Ayarlar"
        }
    },
    en: { 
        common: { save: "Save", cancel: "Cancel", welcome: "Welcome", search: "Search", delete: "Delete" },
        invoice: {
            successTitle: "E-Invoice Issued",
            successDesc: "Document successfully queued to GIB. E-mailed to the customer automatically.",
            btnNew: "NEW INVOICE",
            btnPdf: "DOWNLOAD PDF",
            buyerLabel: "CUSTOMER / INSTITUTION (BUYER)",
            searchCustomer: "Search Customer Title or Tax No...",
            recentCustomers: "Recent Customers",
            balance: "Balance",
            taxOffice: "Tax Off.",
            undefined: "Undefined",
            changeCustomer: "Change Customer",
            notSpecified: "Not specified",
            noAddress: "No registered address found. E-Archive invoice will be issued.",
            invoiceType: "Invoice Type",
            typeSales: "SALES INVOICE",
            typeReturn: "RETURN INVOICE",
            typeTevkifat: "WITHHOLDING INVOICE",
            typeIstisna: "EXEMPTION INVOICE",
            scenario: "Scenario",
            scenTicari: "COMMERCIAL INVOICE",
            scenTemel: "BASIC INVOICE",
            currency: "Currency",
            tcmbRate: "CBRT Rate",
            issueDate: "Issue Date",
            branch: "Branch / Register",
            branchMain: "HQ (Online)",
            addDispatch: "ADD WAYBILL / REFERENCE",
            dispatchNo: "Waybill Number",
            dispatchPlaceholder: "16-Digit Doc No",
            dispatchDate: "Waybill Date",
            thDesc: "Product / Service Description",
            thQty: "Qty",
            thPrice: "Unit Price",
            thDiscount: "Disc.(%)",
            thIsCode: "Exempt Code",
            thOtherTaxes: "Other Taxes",
            thVat: "VAT(%)",
            thTevkifat: "Withholding",
            thNet: "Net Total",
            itemSearch: "Description or product name...",
            stockSearchList: "🔍 Stock Search List",
            stockCards: "Stock Cards",
            stock: "Stock",
            vat: "VAT",
            notFound: "No results found.",
            otvNone: "No SCT",
            otvPercent: "Percentage SCT",
            otvAmount: "Fixed (Unit)",
            otvAmountLabel: "Amount/Rate:",
            tevkifatNone: "No Withholding",
            tevkifatFull: "10/10 (Full)",
            addLine: "ADD NEW LINE",
            noteLabel: "Invoice Footer Note",
            notePlaceholder: "Bank IBAN details, delivery note etc...",
            totSub: "Goods / Services Subtotal",
            totDisc: "Total Discount",
            totVat: "Calculated VAT",
            totOtv: "Calculated SCT",
            totOiv: "Calculated OIV",
            totTevkifat: "(-) Withheld VAT",
            totGrand: "TOTAL INCLUDING TAXES",
            totSys: "System Equivalent (TRY)",
            btnDraft: "SAVE AS DRAFT",
            btnDraftShort: "DRAFT",
            btnSend: "ISSUE E-INVOICE & SEND",
            btnWait: "PLEASE WAIT..."
        },
        adission: {
            successTitle: "E-Ticketing Printed",
            successDesc: "account ticket successfully forwarded to GIB and kitchen printer.",
            salon: "MAIN HALL (INDOOR)",
            teras: "TERRACE",
            bahce: "GARDEN",
            emptyCart: "No products in cart.",
            thProd: "Product",
            thQty: "Qty",
            thTotal: "Total",
            statusNew: "New",
            statusAvailable: "AVAILABLE",
            generalTotal: "Grand Total",
            btnPrinting: "PRINTING...",
            btnKitchen: "KITCHEN / BAR",
            btnClosing: "CLOSING...",
            btnCheckout: "CHECKOUT",
            standbyTitle: "Register Standby",
            standbyDesc: "Select a table from the left to process.",
            minutes: "min",
            unknown: "Unknown",
            emptyAdission: "Ticket Empty",
            errEmpty: "No items added to the table yet.",
            errKitchenEmpty: "No new items to send to the kitchen.",
            kitchenSuccess: "Sent to Kitchen",
            kitchenSuccessDesc: "new items sent to IP kitchen printer successfully."
        },
        terminal: {
            customer: "Customer",
            openAccount: "Open Account",
            liveRateOn: "Live Rate On",
            liveRateOff: "Live Rate Off",
            liveRateTooltip: "When active, product foreign exchange rates are instantly converted to TRY during sale.",
            coupon: "Coupon",
            points: "Points",
            ref: "Ref",
            pending: "Pending",
            quickSale: "Quick Sale",
            restoPos: "Resto-Pos",
            eInvoice: "E-Invoice",
            eMustahsil: "E-Producer",
            eSmm: "E-SMM",
            retailCustomer: "Retail Customer",
            customerSelection: "Customer Selection (F8)",
            searchPlaceholder: "Search...",
            escClose: "ESC - Close",
            pendingSales: "Pending Sales (F9)",
            noPendingSales: "No pending sales.",
            openBtn: "OPEN",
            deleteBtn: "DEL",
            productsText: "Product",
            suspendSale: "Suspend Sale",
            suspendLabelPlaceholder: "Label / Name (e.g. Table 5 or Customer Name)",
            btnSuspend: "Suspend",
            extrasDiscounts: "Extras & Discounts",
            cartDiscount: "Cart Discount",
            enterCode: "ENTER CODE",
            usePoints: "Use Points",
            available: "Available",
            orderNote: "Order Note / Reference",
            notePlaceholder: "Document, plate or table no...",
            confirm: "CONFIRM",
            completePayment: "Complete Payment",
            cartSubtotal: "Cart Subtotal",
            manualDiscount: "Manual Discount / Pts",
            autoRewards: "Auto Rewards",
            campaignDiscount: "Campaign Discount",
            pointsToEarn: "Points to Earn",
            freeInCart: "Free in Cart",
            grandTotal: "Grand Total",
            selectVaultBank: "Target Vault / Bank",
            balance: "Balance",
            noVaultFound: "No vault found for this payment type.",
            selectInstallment: "Select Installment / POS Commission",
            deduction: "Deduction",
            cancelGiveUp: "Cancel / Give Up",
            processing: "PROCESSING...",
            confirmFinish: "CONFIRM & FINISH"
        },
        menu: {
            workspace: "WORKSPACE",
            pos: "POS Terminal",
            kds: { parent: "Restaurant & KDS", kitchen: "Kitchen Display (KDS)", qmenu: "QR Ordering & Menu", courier: "Courier Operations" },
            hub: { parent: "Periodya Hub", hub: "Hub Dashboard", dispute: "Dispute Resolution Center", cart: "Network Cart", orders: "Requests & Orders", catalog: "B2B Catalog", finance: "Finance & Growth", rfq: "RFQs & Contracts" },
            dealer: { parent: "Dealer Network", dealers: "Dealers", catalog: "B2B Catalog", orders: "Order Approvals", refunds: "Refunds", banners: "Banner Management", settings: "Settings" },
            operations: "OPERATIONS",
            calendar: "Global Calendar",
            staffme: "Staff Portal",
            tasks: { parent: "Task Center", tower: "Task Tower" },
            signatures: { parent: "Signatures", board: "Signature Board", envelopes: "Documents & Envelopes", inbox: "Incoming Requests", completed: "Completed" },
            recon: { parent: "Reconciliation", open: "Open Reconciliations", all: "All Reconciliations", disputes: "Dispute Management" },
            accounting: "Financial Management",
            sales: { parent: "Sales Management", all: "All Sales", radar: "Revenue Intelligence" },
            customers: { parent: "Current Accounts", customers: "Customers", suppliers: "Suppliers" },
            inventory: { parent: "Inventory", general: "Inventory Overview", warehouse: "Warehouses & Stock", mfg: "Manufacturing Control Center" },
            assets: { parent: "Assets & Fixtures", list: "Asset List", assignments: "Assignment Center", mnx: "Maintenance & Expenses" },
            service: { parent: "Service Desk", dash: "Service Dashboard", workOrders: "Work Orders", new: "New Work Order", calendar: "Service Appointments", tv: "Workshop Live TV", field: "Field Planning Board", fieldDash: "Field Service Panel" },
            offers: "Quotes",
            salesx: "SalesX Field Panel",
            hr: { parent: "Human Resources", employees: "Employees", perf: "Performance & Targets" },
            campaign: { parent: "Campaign Engine", dash: "Dashboard", new: "New Setup", active: "Active Campaigns", scheduled: "Scheduled Campaigns", perf: "Performance Analytics" },
            analytics: "ANALYTICS & MANAGEMENT",
            reports: { parent: "Business Intelligence", ceo: "CEO Dashboard", detail: "Detailed Analysis" },
            fintech: "Fintech Tower",
            advisor: "Financial Advisor",
            anomaly: "Anomalies",
            system: "SYSTEM",
            import: "Advanced Import",
            integrations: "Integrations",
            help: "Help Center",
            billing: { parent: "Billing & Market", panel: "Billing Dashboard", store: "App Store" },
            settings: "Settings"
        }
    },
    de: { 
        common: { save: "Speichern", cancel: "Abbrechen", welcome: "Willkommen", search: "Suche", delete: "Löschen" },
        invoice: {
            successTitle: "E-Rechnung erstellt",
            successDesc: "Dokument erfolgreich an GIB gesendet. Automatisch an den Kunden per E-Mail gesendet.",
            btnNew: "NEUE RECHNUNG",
            btnPdf: "PDF HERUNTERLADEN",
            buyerLabel: "KUNDE / INSTITUTION (KÄUFER)",
            searchCustomer: "Kundenname oder Steuernummer suchen...",
            recentCustomers: "Kürzlich verwendete Kunden",
            balance: "Saldo",
            taxOffice: "Finanzamt",
            undefined: "Undefiniert",
            changeCustomer: "Kunde wechseln",
            notSpecified: "Nicht angegeben",
            noAddress: "Keine Adresse gefunden. E-Archiv-Rechnung wird erstellt.",
            invoiceType: "Rechnungsart",
            typeSales: "VERKAUFSRECHNUNG",
            typeReturn: "RÜCKGABERECHNUNG",
            typeTevkifat: "QUELLENSTEUERRECHNUNG",
            typeIstisna: "BEFREIUNGSRECHNUNG",
            scenario: "Szenario",
            scenTicari: "HANDELSRECHNUNG",
            scenTemel: "BASISRECHNUNG",
            currency: "Währung",
            tcmbRate: "CBRT Kurs",
            issueDate: "Ausstellungsdatum",
            branch: "Filiale / Kasse",
            branchMain: "Zentrale (Online)",
            addDispatch: "LIEFERSCHEIN / REFERENZ HINZUFÜGEN",
            dispatchNo: "Lieferscheinnummer",
            dispatchPlaceholder: "16-stellige Dokument-Nr",
            dispatchDate: "Lieferscheindatum",
            thDesc: "Produkt / Leistungsbeschreibung",
            thQty: "Menge",
            thPrice: "Einzelpreis",
            thDiscount: "Rabatt(%)",
            thIsCode: "Befreiungscode",
            thOtherTaxes: "Andere Steuern",
            thVat: "MwSt(%)",
            thTevkifat: "Quellensteuer",
            thNet: "Nettobetrag",
            itemSearch: "Beschreibung oder Produktname...",
            stockSearchList: "🔍 Bestandssuche",
            stockCards: "Lagerkarten",
            stock: "Bestand",
            vat: "MwSt",
            notFound: "Keine Ergebnisse gefunden.",
            otvNone: "Keine SCT",
            otvPercent: "Prozentuale SCT",
            otvAmount: "Fest (Einheit)",
            otvAmountLabel: "Betrag/Rate:",
            tevkifatNone: "Ohne Abzug",
            tevkifatFull: "10/10 (Voll)",
            addLine: "NEUE ZEILE",
            noteLabel: "Rechnungsfußnote",
            notePlaceholder: "Bank-IBAN-Details, Lieferschein usw...",
            totSub: "Waren / Dienstleistungen Zwischensumme",
            totDisc: "Gesamtrabatt",
            totVat: "Berechnete MwSt",
            totOtv: "Berechnete SCT",
            totOiv: "Berechnete OIV",
            totTevkifat: "(-) Einbehaltene MwSt",
            totGrand: "GESAMTSUMME INKLUSIVE STEUERN",
            totSys: "Systemäquivalent (TRY)",
            btnDraft: "ALS ENTWURF SPEICHERN",
            btnDraftShort: "ENTWURF",
            btnSend: "E-RECHNUNG ERSTELLEN & SENDEN",
            btnWait: "BITTE WARTEN..."
        },
        adission: {
            successTitle: "E-Bon gedruckt",
            successDesc: "Konto-Bon erfolgreich an GIB und Küchendrucker übermittelt.",
            salon: "HAUPTSAAL (INNEN)",
            teras: "TERRASSE",
            bahce: "GARTEN",
            emptyCart: "Keine Produkte im Warenkorb.",
            thProd: "Produkt",
            thQty: "Menge",
            thTotal: "Gesamt",
            statusNew: "Neu",
            statusAvailable: "VERFÜGBAR",
            generalTotal: "Gesamtsumme",
            btnPrinting: "WIRD GEDRUCKT...",
            btnKitchen: "KÜCHE / BAR",
            btnClosing: "WIRD GESCHLOSSEN...",
            btnCheckout: "ABRECHNEN",
            standbyTitle: "Kasse in Bereitschaft",
            standbyDesc: "Wählen Sie links einen Tisch zur Bearbeitung.",
            minutes: "min",
            unknown: "Unbekannt",
            emptyAdission: "Tisch Ist Leer",
            errEmpty: "Es wurden noch keine Artikel zum Tisch hinzugefügt.",
            errKitchenEmpty: "Keine neuen Artikel für die Küche.",
            kitchenSuccess: "An Küche gesendet",
            kitchenSuccessDesc: "neue Artikel erfolgreich an den IP-Küchendrucker gesendet."
        },
        terminal: {
            customer: "Kunde",
            openAccount: "Offenes Konto",
            liveRateOn: "Live-Kurse Ein",
            liveRateOff: "Live-Kurse Aus",
            liveRateTooltip: "Wenn aktiv, werden Fremdwährungen während des Verkaufs sofort in TRY umgerechnet.",
            coupon: "Gutschein",
            points: "Punkte",
            ref: "Ref",
            pending: "Ausstehend",
            quickSale: "Schnellverkauf",
            restoPos: "Resto-Pos",
            eInvoice: "E-Rechnung",
            eMustahsil: "E-Erzeuger",
            eSmm: "E-SMM",
            retailCustomer: "Einzelhandelskunde",
            customerSelection: "Kundenauswahl (F8)",
            searchPlaceholder: "Suchen...",
            escClose: "ESC - Schließen",
            pendingSales: "Ausstehende Verkäufe (F9)",
            noPendingSales: "Keine ausstehenden Verkäufe.",
            openBtn: "ÖFFNEN",
            deleteBtn: "LÖS",
            productsText: "Produkt",
            suspendSale: "Verkauf paussieren",
            suspendLabelPlaceholder: "Etikett / Name (z.B. Tisch 5 oder Kundenname)",
            btnSuspend: "Pausieren",
            extrasDiscounts: "Extras & Rabatte",
            cartDiscount: "Warenkorbrabatt",
            enterCode: "CODE EINGEBEN",
            usePoints: "Punkte Verwenden",
            available: "Verfügbar",
            orderNote: "Bestellnotiz / Referenz",
            notePlaceholder: "Dokument, Kennzeichen oder Tischnummer...",
            confirm: "BESTÄTIGEN",
            completePayment: "Zahlung Abschließen",
            cartSubtotal: "Warenkorb-Zwischensumme",
            manualDiscount: "Manueller Rabatt / Pkt",
            autoRewards: "Auto-Belohnungen",
            campaignDiscount: "Kampagnenrabatt",
            pointsToEarn: "Zu verdienende Punkte",
            freeInCart: "Kostenlos im Warenkorb",
            grandTotal: "Gesamtsumme",
            selectVaultBank: "Zielkasse / Bank",
            balance: "Saldo",
            noVaultFound: "Keine Kasse für diese Zahlungsart gefunden.",
            selectInstallment: "Ratenzahlung / POS-Provision Wählen",
            deduction: "Abzug",
            cancelGiveUp: "Abbrechen",
            processing: "WIRD BEARBEITET...",
            confirmFinish: "BESTÄTIGEN & ABSCHLIESSEN"
        },
        menu: {
            workspace: "ARBEITSBEREICH",
            pos: "Kassensystem (POS)",
            kds: { parent: "Gastro & KDS", kitchen: "Küchendisplay (KDS)", qmenu: "QR Bestellungen & Menü", courier: "Kurier-Betrieb" },
            hub: { parent: "Periodya Hub", hub: "Hub-Dashboard", dispute: "Streitbeilegungszentrum", cart: "Netzwerk-Warenkorb", orders: "Anfragen & Bestellungen", catalog: "B2B-Katalog", finance: "Finanzen & Wachstum", rfq: "Ausschreibungen & Verträge" },
            dealer: { parent: "Händlernetzwerk", dealers: "Händler", catalog: "B2B-Katalog", orders: "Bestellgenehmigungen", refunds: "Rückerstattungen", banners: "Banner-Management", settings: "Einstellungen" },
            operations: "OPERATIONEN",
            calendar: "Globaler Kalender",
            staffme: "Mitarbeiter-Portal",
            tasks: { parent: "Aufgabenzentrum", tower: "Aufgaben-Turm" },
            signatures: { parent: "Unterschriften", board: "Signatur-Board", envelopes: "Dokumente & Umschläge", inbox: "Eingehende Anfragen", completed: "Abgeschlossen" },
            recon: { parent: "Abstimmung", open: "Offene Abstimmungen", all: "Alle Abstimmungen", disputes: "Konfliktmanagement" },
            accounting: "Finanzmanagement",
            sales: { parent: "Vertriebsmanagement", all: "Alle Verkäufe", radar: "Umsatz-Intelligenz" },
            customers: { parent: "Kunden & Lieferanten", customers: "Kunden", suppliers: "Lieferanten" },
            inventory: { parent: "Inventar", general: "Inventarübersicht", warehouse: "Lager & Bestand", mfg: "Produktions­kontrollzentrum" },
            assets: { parent: "Anlagen & Ausstattung", list: "Anlagenliste", assignments: "Zuweisungszentrum", mnx: "Wartung & Ausgaben" },
            service: { parent: "Service Desk", dash: "Service-Dashboard", workOrders: "Arbeitsaufträge", new: "Neuer Arbeitsauftrag", calendar: "Service-Termine", tv: "Werkstatt Live-TV", field: "Einsatzplanung", fieldDash: "Service-Einsatzpanel" },
            offers: "Angebote",
            salesx: "SalesX Außendienst",
            hr: { parent: "Personalwesen", employees: "Mitarbeiter", perf: "Leistung & Ziele" },
            campaign: { parent: "Kampagnen-Engine", dash: "Dashboard", new: "Neues Setup", active: "Aktive Kampagnen", scheduled: "Geplante Kampagnen", perf: "Leistungsanalysen" },
            analytics: "ANALYTIK & MANAGEMENT",
            reports: { parent: "Business Intelligence", ceo: "CEO-Dashboard", detail: "Detaillierte Analyse" },
            fintech: "Fintech-Turm",
            advisor: "Steuerberater",
            anomaly: "Anomalien",
            system: "SYSTEM",
            import: "Erweiterter Import",
            integrations: "Integrationen",
            help: "Hilfe-Center",
            billing: { parent: "Abrechnung & Store", panel: "Abrechnungs-Dashboard", store: "App-Store" },
            settings: "Einstellungen"
        }
    }
};

type Language = "tr" | "en" | "de";

interface LanguageContextProps {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string, variables?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextProps>({
    language: "tr",
    setLanguage: () => {},
    t: (key) => key,
});

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [language, setLanguageState] = useState<Language>("tr");
    const [dictionaries, setDictionaries] = useState<Record<string, any>>(defaultDictionaries);

    useEffect(() => {
        // Load user's preferred language from local storage
        const savedLang = localStorage.getItem("periodya_lang") as Language;
        if (savedLang && ["tr", "en", "de"].includes(savedLang)) {
            setLanguageState(savedLang);
        }

        // Future: Fetch extended dictionaries from a server or dynamic imports here
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem("periodya_lang", lang);
        // Optionally reload or sync state to server
    };

    const t = (key: string, variables?: Record<string, any>): string => {
        const keys = key.split(".");
        let value = dictionaries[language];

        for (const k of keys) {
            if (value && typeof value === 'object') {
                value = value[k];
            } else {
                value = undefined;
                break;
            }
        }

        // If string not found in target language, fallback to TR or just return the key
        if (value === undefined) {
             let trValue = dictionaries["tr"];
             for (const k of keys) {
                if (trValue && typeof trValue === 'object') trValue = trValue[k];
                else { trValue = undefined; break; }
             }
             value = trValue !== undefined ? trValue : key;
        }

        if (typeof value !== 'string') return key;

        // Replace variables e.g. {name} -> variables.name
        if (variables) {
            return value.replace(/\{(\w+)\}/g, (_, vKey) => {
                return variables[vKey] !== undefined ? variables[vKey] : `{${vKey}}`;
            });
        }

        return value;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
