export type EventType =
    | 'SIGNATURE_INVITATION_SENT'
    | 'SIGNATURE_COMPLETED'
    | 'SIGNATURE_REJECTED'
    | 'RECONCILIATION_SENT'
    | 'RECONCILIATION_VIEWED'
    | 'RECONCILIATION_DISPUTED'
    | 'DISPUTE_RESOLVED'
    | 'OTP_SENT'
    | 'OTP_FAILED'
    | 'MAIL_SENT'
    | 'MAIL_FAILED'
    | 'TASK_CREATED'
    | 'NETWORK_MEMBERSHIP_CREATED'
    | 'NETWORK_PROFILE_CREATED'
    | 'NETWORK_PROFILE_UPDATED'
    | 'NETWORK_INVITATION_SENT'
    | 'NETWORK_INVITATION_ACCEPTED'
    | 'NETWORK_INVITATION_REJECTED'
    | 'NETWORK_RELATIONSHIP_ACTIVATED'
    | 'NETWORK_TRUST_SCORE_UPDATED'
    | 'NETWORK_PROFILE_COMPLETION_UPDATED'
    | 'NETWORK_RELATIONSHIP_HEALTH_UPDATED'
    | 'NETWORK_COMPANY_VERIFIED'
    | 'NETWORK_COMPANY_RESTRICTED'
    | 'NETWORK_CAPABILITY_UPDATED'
    | 'NETWORK_CATEGORY_SIGNAL_UPDATED'
    | 'NETWORK_RECOMMENDATION_GENERATED'
    | 'NETWORK_RFQ_SUPPLIERS_SUGGESTED'
    | 'NETWORK_INVENTORY_SIGNAL_CREATED'
    | 'NETWORK_TRADE_OPPORTUNITY_CREATED'
    | 'NETWORK_RFQ_DRAFT_GENERATED'
    | 'NETWORK_SUPPLIER_SCORE_COMPUTED'
    | 'NETWORK_RFQ_ROUTING_PREPARED'
    | 'NETWORK_RFQ_WAVE_ROUTED'
    | 'NETWORK_RFQ_FALLBACK_TRIGGERED'
    | 'NETWORK_ROUTING_POLICY_UPDATED'
    | 'NETWORK_AI_MATCH_GENERATED';

export interface AppEvent {
    type: EventType;
    tenantId?: string;
    companyId?: string;
    userId?: string;
    relatedEntityType?: string;
    relatedEntityId?: string;
    title?: string;
    message?: string;
    meta?: Record<string, any>;
}
