import prisma from '@/lib/prisma';

export const dynamic = 'force-dynamic';

export default async function NetworkGrowthActionsPage() {
    const actions = await prisma.networkGrowthAction.findMany({
        orderBy: { createdAt: 'desc' },
        take: 100
    });

    return (
        <div className="p-6 space-y-6 max-w-7xl mx-auto">
            <div>
                <h1 className="text-3xl font-bold tracking-tight text-slate-900 border-b pb-4">Growth Actions</h1>
                <p className="text-slate-500 mt-2">
                    Specific executable tasks (Discovery Candidates, Invites) generated by Growth Triggers.
                </p>
            </div>

            <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
                <div className="px-6 py-4 border-b border-slate-200 bg-slate-50/50">
                    <h2 className="text-lg font-semibold text-slate-800 tracking-tight">Autonomous Outreach & Expansion Queue</h2>
                </div>
                <div className="p-0">
                    {actions.length === 0 ? (
                        <div className="py-12 text-center text-slate-500 text-sm">
                            No growth actions produced yet. Waiting for triggers.
                        </div>
                    ) : (
                        <div className="overflow-x-auto">
                            <table className="w-full text-sm text-left">
                                <thead className="bg-slate-50 text-slate-500 font-semibold border-b">
                                    <tr>
                                        <th className="px-6 py-3">Created At</th>
                                        <th className="px-6 py-3">Action Type</th>
                                        <th className="px-6 py-3">Trigger ID</th>
                                        <th className="px-6 py-3">Target</th>
                                        <th className="px-6 py-3">Status</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-slate-100">
                                    {actions?.map((action) => (
                                        <tr key={action.id} className="hover:bg-slate-50/50 transition-colors">
                                            <td className="px-6 py-4 font-medium whitespace-nowrap text-slate-900">
                                                {new Date(action.createdAt).toLocaleString()}
                                            </td>
                                            <td className="px-6 py-4">
                                                <span className="font-semibold text-indigo-600">{action.actionType}</span>
                                            </td>
                                            <td className="px-6 py-4 font-mono text-xs text-slate-500 truncate max-w-[150px]">
                                                {action.triggerId}
                                            </td>
                                            <td className="px-6 py-4 text-slate-700">
                                                {action.targetRef ? `${action.targetType}: ${action.targetRef}` : 'Auto / System'}
                                            </td>
                                            <td className="px-6 py-4">
                                                <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${action.status === 'PENDING' ? 'bg-orange-100 text-orange-800' : 'bg-slate-100 text-slate-800'}`}>
                                                    {action.status}
                                                </span>
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
