export const TRUST_WEIGHTS = {
    IDENTITY_VERIFIED: 0.35,
    TRADE_COMPLETION: 0.25,
    SHIPPING_RELIABILITY: 0.20,
    PAYMENT_RELIABILITY: 0.10,
    DISPUTE_RATE: 0.10, // inverse impact
};

export const TRUST_THRESHOLDS = {
    VERIFIED_HIGH: 0.85,
    HIGH: 0.70,
    MEDIUM: 0.40,
    LOW: 0.0,
};

export const SIGNAL_TYPES = {
    IDENTITY_VERIFIED: "IDENTITY_VERIFIED",
    TRADE_COMPLETION_RATE: "TRADE_COMPLETION_RATE",
    SHIPPING_RELIABILITY: "SHIPPING_RELIABILITY",
    PAYMENT_RELIABILITY: "PAYMENT_RELIABILITY",
    DISPUTE_RATE: "DISPUTE_RATE",
};
